[workspace]
members = [
    "rust/inkpod-core",
    "rust/inkpod-ffi",
    "rust/inkpod-format",
    "rust/inkpod-image",
]
exclude = ["rust/inkpod-format/fuzz"]
resolver = "3"

[workspace.package]
version = "0.2.5"
edition = "2024"
rust-version = "1.85"
license = "GPL-3.0-only"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
