#include "inkpod/core_ffi.h"

#include <stdint.h>

_Static_assert(INKPOD_ABI_VERSION == 31U, "unexpected ABI version");
_Static_assert(sizeof(InkpodIoConfig) == 48U, "I/O config layout drift");
_Static_assert(sizeof(InkpodIoPath) == 24U, "I/O path layout drift");
_Static_assert(sizeof(InkpodIoRequest) == 72U, "I/O request layout drift");
_Static_assert(sizeof(InkpodIoJobInfo) == 104U, "I/O job info layout drift");
_Static_assert(sizeof(InkpodIoFileIdentity) == 32U, "I/O identity layout drift");
_Static_assert(sizeof(InkpodIoItemInfo) == 80U, "I/O item layout drift");
_Static_assert(sizeof(InkpodIoCacheInfo) == 120U, "I/O cache info layout drift");
_Static_assert(sizeof(InkpodIoRecoveryPairProof) == 168U, "I/O recovery pair proof layout drift");
_Static_assert(sizeof(InkpodIoRecoveryMetadata) == 328U, "I/O recovery metadata layout drift");
_Static_assert(sizeof(InkpodIoRecoveryArtifactStamp) == 80U, "I/O recovery artifact stamp layout drift");
_Static_assert(sizeof(InkpodIoRecoveryArtifactProof) == 168U, "I/O recovery artifact proof layout drift");
_Static_assert(INKPOD_IO_OPEN_RASTER_PAIR == UINT32_C(22), "raster-pair open kind drift");
_Static_assert(INKPOD_IO_REVERT_CURRENT == (UINT64_C(1) << 4), "revert-current flag drift");
_Static_assert(INKPOD_IO_RECOVERY_ARTIFACT_READONLY == (UINT32_C(1) << 0), "recovery artifact flag drift");
_Static_assert(INKPOD_IO_RECOVERY_PAIR_NONE == UINT32_C(0), "recovery pair none kind drift");
_Static_assert(INKPOD_IO_RECOVERY_PAIR_COMMITTED == UINT32_C(1), "recovery pair committed kind drift");
_Static_assert(INKPOD_IO_RECOVERY_PAIR_PLANNED == UINT32_C(2), "recovery pair planned kind drift");
_Static_assert(INKPOD_IO_RECOVERY_PAIR_REPAIR_NEEDED == UINT32_C(3), "recovery pair repair kind drift");
_Static_assert(INKPOD_IO_RESULT_AUTHORITY_REPAIRED == (UINT64_C(1) << 3), "I/O authority-repaired flag drift");
_Static_assert(INKPOD_IO_RESULT_AUTHORITY_REVOKED == (UINT64_C(1) << 4), "I/O authority-revoked flag drift");
_Static_assert(INKPOD_SEQUENCE_SWITCH_SOURCE_RECOVERY_REQUIRED == (UINT32_C(1) << 1), "sequence preservation flag drift");
_Static_assert(sizeof(InkpodSubpaletteSourceInput) == 32U, "subpalette source layout drift");
_Static_assert(sizeof(InkpodSubpaletteRasterInput) == 32U, "subpalette raster layout drift");
_Static_assert(sizeof(InkpodSubpaletteInfo) == 32U, "subpalette info layout drift");
_Static_assert(sizeof(InkpodSubpaletteItemInfo) == 40U, "subpalette item layout drift");
_Static_assert(sizeof(InkpodCoreConfig) == 16U, "core config layout drift");
_Static_assert(sizeof(InkpodSnapshotOptions) == 16U, "snapshot options layout drift");
_Static_assert(sizeof(InkpodPersistenceInfo) == 72U, "persistence info layout drift");
_Static_assert(sizeof(InkpodCompactionPlan) == 128U, "compaction plan layout drift");
_Static_assert(sizeof(InkpodSnapshotView) == 48U, "snapshot view layout drift");
_Static_assert(sizeof(InkpodSnapshotRenderPass) == 48U, "render pass layout drift");
_Static_assert(sizeof(InkpodSnapshotRenderPlan) == 40U, "render plan layout drift");
_Static_assert(sizeof(InkpodCellCreateOptions) == 48U, "cell options layout drift");
_Static_assert(sizeof(InkpodCellCreationOptions) == 64U, "cell creation options layout drift");
_Static_assert(sizeof(InkpodCellCreationPlanItem) == 140U, "cell creation plan item layout drift");
_Static_assert(sizeof(InkpodDocumentInfo) == 232U, "document info layout drift");
_Static_assert(sizeof(InkpodUtf8Span) == 16U, "UTF-8 span layout drift");
_Static_assert(sizeof(InkpodUtf8Buffer) == 24U, "UTF-8 buffer layout drift");
_Static_assert(sizeof(InkpodCutMetadataInput) == 88U, "Cut metadata input layout drift");
_Static_assert(sizeof(InkpodCutMetadataBuffer) == 128U, "Cut metadata buffer layout drift");
_Static_assert(sizeof(InkpodCutDefaultsInput) == 56U, "Cut defaults layout drift");
_Static_assert(sizeof(InkpodCutMemberInput) == 48U, "Cut member input layout drift");
_Static_assert(sizeof(InkpodCutCreateRequest) == 72U, "Cut create request layout drift");
_Static_assert(sizeof(InkpodCutUpdateRequest) == 40U, "Cut update request layout drift");
_Static_assert(sizeof(InkpodCutInfo) == 144U, "Cut info layout drift");
_Static_assert(sizeof(InkpodCutMemberInfo) == 56U, "Cut member info layout drift");
_Static_assert(sizeof(InkpodCutSequenceEditOperation) == 104U, "Cut sequence operation layout drift");
_Static_assert(sizeof(InkpodCutSequenceEditRequest) == 48U, "Cut sequence request layout drift");
_Static_assert(sizeof(InkpodCutSequenceEditResult) == 40U, "Cut sequence result layout drift");
_Static_assert(sizeof(InkpodDocumentThumbnailBuffer) == 56U, "document thumbnail layout drift");
_Static_assert(sizeof(InkpodResourceUsage) == 136U, "resource usage layout drift");
_Static_assert(sizeof(InkpodSnapshotSourceIdentity) == 40U, "snapshot source identity layout drift");
_Static_assert(sizeof(InkpodSequenceCatalogInfo) == 32U, "sequence catalog layout drift");
_Static_assert(sizeof(InkpodHistoryItem) == 24U, "history item layout drift");
_Static_assert(sizeof(InkpodStrokeSample) == 24U, "stroke sample layout drift");
_Static_assert(sizeof(InkpodStrokeInput) == 72U, "stroke input layout drift");
_Static_assert(sizeof(InkpodGeometryPoint) == 16U, "geometry point layout drift");
_Static_assert(sizeof(InkpodGeometryPointResolveInput) == 56U, "geometry resolve input layout drift");
_Static_assert(sizeof(InkpodGeometryPointResolveResult) == 24U, "geometry resolve result layout drift");
_Static_assert(sizeof(InkpodGeometryInput) == 104U, "geometry input layout drift");
_Static_assert(sizeof(InkpodGeometryPreviewInfo) == 32U, "geometry preview layout drift");
_Static_assert(sizeof(InkpodEditorBrushOptions) == 20U, "editor brush layout drift");
_Static_assert(sizeof(InkpodStrokeSampleSpan) == 40U, "stroke span layout drift");
_Static_assert(sizeof(InkpodViewInput) == 48U, "view input layout drift");
_Static_assert(sizeof(InkpodSnapshotTransform) == 48U, "snapshot transform layout drift");
_Static_assert(sizeof(InkpodSnapshotGuide) == 24U, "snapshot guide layout drift");
_Static_assert(sizeof(InkpodSnapshotOverlay) == 56U, "snapshot overlay layout drift");
_Static_assert(sizeof(InkpodShootingFrameInput) == 64U, "shooting frame input layout drift");
_Static_assert(sizeof(InkpodShootingFramePoint) == 16U, "shooting frame point layout drift");
_Static_assert(sizeof(InkpodShootingFrameInfo) == 136U, "shooting frame info layout drift");
_Static_assert(sizeof(InkpodSnapshotShootingFrameView) == 40U, "shooting frame view layout drift");
_Static_assert(sizeof(InkpodSavedSelectionInfo) == 40U, "saved selection info layout drift");
_Static_assert(sizeof(InkpodObjectId) == 32U, "object id layout drift");
_Static_assert(sizeof(InkpodPrimitiveRequestV3) == 120U, "primitive request layout drift");
_Static_assert(sizeof(InkpodPrimitiveResultV3) == 48U, "primitive result layout drift");
_Static_assert(sizeof(InkpodRasterAssetInputV3) == 56U, "raster asset layout drift");
_Static_assert(sizeof(InkpodObjectInfoV3) == 72U, "object info layout drift");
_Static_assert(sizeof(InkpodSnapshotInfoV3) == 80U, "snapshot info layout drift");
_Static_assert(sizeof(InkpodSnapshotTileInfoV3) == 56U, "snapshot tile info layout drift");
_Static_assert(sizeof(InkpodBufferCopyV3) == 56U, "buffer copy layout drift");
_Static_assert(sizeof(InkpodRasterSourceInput) == 96U, "raster source layout drift");
_Static_assert(sizeof(InkpodLightTableItemInput) == 168U, "light-table input layout drift");
_Static_assert(sizeof(InkpodSequenceCellInput) == 120U, "sequence cell layout drift");
_Static_assert(sizeof(InkpodSequenceInput) == 40U, "sequence input layout drift");
_Static_assert(sizeof(InkpodSequenceSwitchRequest) == 88U, "sequence switch request layout drift");
_Static_assert(sizeof(InkpodSequenceStepPlan) == 96U, "sequence step plan layout drift");
_Static_assert(sizeof(InkpodMotionCheckInput) == 16U, "motion input layout drift");
_Static_assert(sizeof(InkpodMotionFrame) == 40U, "motion frame layout drift");
_Static_assert(sizeof(InkpodLayerThumbnailBuffer) == 80U, "layer thumbnail layout drift");
_Static_assert(sizeof(InkpodScopedColorReplaceInput) == 120U, "scoped replace input layout drift");
_Static_assert(sizeof(InkpodScopedColorReplacePreview) == 40U, "scoped replace preview layout drift");
_Static_assert(sizeof(InkpodSequenceSourceIdentity) == 32U, "sequence identity layout drift");
_Static_assert(sizeof(InkpodBatchPairPreviewInfo) == 40U, "pair preview info layout drift");
_Static_assert(sizeof(InkpodBatchPairCandidate) == 64U, "pair candidate layout drift");
_Static_assert(sizeof(InkpodInkScriptSourceInput) == 56U, "InkScript source input layout drift");
_Static_assert(sizeof(InkpodInkScriptSourceSummary) == 72U, "InkScript source summary layout drift");
_Static_assert(sizeof(InkpodInkScriptUtf8Buffer) == 48U, "InkScript UTF-8 buffer layout drift");
_Static_assert(sizeof(InkpodInkScriptDiagnostic) == 128U, "InkScript diagnostic layout drift");
_Static_assert(sizeof(InkpodInkScriptDiagnosticBuffer) == 96U, "InkScript diagnostic buffer layout drift");
_Static_assert(sizeof(InkpodInkScriptParameterChoice) == 56U, "InkScript parameter choice layout drift");
_Static_assert(sizeof(InkpodInkScriptCompileRequest) == 80U, "InkScript compile request layout drift");
_Static_assert(sizeof(InkpodInkScriptProgramSummary) == 152U, "InkScript program summary layout drift");
_Static_assert(sizeof(InkpodInkScriptJournalEvent) == 24U, "InkScript event layout drift");
_Static_assert(sizeof(InkpodInkScriptExportRequest) == 96U, "InkScript export request layout drift");
_Static_assert(sizeof(InkpodInkScriptFragmentSummary) == 88U, "InkScript fragment summary layout drift");
_Static_assert(INKPOD_EDITOR_TOOL_GEOMETRY_LINE == 1011U, "geometry line tool code drift");
_Static_assert(INKPOD_EDITOR_TOOL_GEOMETRY_CURVE == 1012U, "geometry curve tool code drift");
_Static_assert(INKPOD_EDITOR_TOOL_GEOMETRY_RECTANGLE == 1013U, "geometry rectangle tool code drift");
_Static_assert(INKPOD_EDITOR_TOOL_GEOMETRY_ELLIPSE == 1014U, "geometry ellipse tool code drift");
_Static_assert(INKPOD_EDITOR_TOOL_GEOMETRY_POLYGON == 1015U, "geometry polygon tool code drift");
_Static_assert(INKPOD_EDITOR_TOOL_GEOMETRY_POLYLINE == 1016U, "geometry polyline tool code drift");

int inkpod_header_c11_smoke(void) {
    InkpodSnapshotView view = {0};
    InkpodInkScriptSourceInput source = {0};
    view.struct_size = (uint32_t)sizeof(view);
    source.struct_size = (uint32_t)sizeof(source);
    source.version = INKPOD_INKSCRIPT_RECORD_VERSION;
    return view.struct_size == 0U || source.struct_size == 0U;
}
