#include "inkpod/core_ffi.h"

#include <stdint.h>

_Static_assert(INKPOD_ABI_VERSION == 15U, "unexpected ABI version");
_Static_assert(sizeof(InkpodCoreConfig) == 16U, "core config layout drift");
_Static_assert(sizeof(InkpodSnapshotOptions) == 16U, "snapshot options layout drift");
_Static_assert(sizeof(InkpodPersistenceInfo) == 72U, "persistence info layout drift");
_Static_assert(sizeof(InkpodCompactionPlan) == 128U, "compaction plan layout drift");
_Static_assert(sizeof(InkpodSnapshotView) == 48U, "snapshot view layout drift");
_Static_assert(sizeof(InkpodSnapshotRenderPass) == 48U, "render pass layout drift");
_Static_assert(sizeof(InkpodSnapshotRenderPlan) == 64U, "render plan layout drift");
_Static_assert(sizeof(InkpodCellCreateOptions) == 48U, "cell options layout drift");
_Static_assert(sizeof(InkpodCellCreationOptions) == 64U, "cell creation options layout drift");
_Static_assert(sizeof(InkpodCellCreationPlanItem) == 144U, "cell creation plan item layout drift");
_Static_assert(sizeof(InkpodDocumentInfo) == 232U, "document info layout drift");
_Static_assert(sizeof(InkpodUtf8Span) == 16U, "UTF-8 span layout drift");
_Static_assert(sizeof(InkpodUtf8Buffer) == 24U, "UTF-8 buffer layout drift");
_Static_assert(sizeof(InkpodCutMetadataInput) == 88U, "Cut metadata input layout drift");
_Static_assert(sizeof(InkpodCutMetadataBuffer) == 128U, "Cut metadata buffer layout drift");
_Static_assert(sizeof(InkpodCutDefaultsInput) == 64U, "Cut defaults layout drift");
_Static_assert(sizeof(InkpodCutMemberInput) == 48U, "Cut member input layout drift");
_Static_assert(sizeof(InkpodCutCreateRequest) == 72U, "Cut create request layout drift");
_Static_assert(sizeof(InkpodCutUpdateRequest) == 40U, "Cut update request layout drift");
_Static_assert(sizeof(InkpodCutInfo) == 144U, "Cut info layout drift");
_Static_assert(sizeof(InkpodCutMemberInfo) == 56U, "Cut member info layout drift");
_Static_assert(sizeof(InkpodCutSequenceEditOperation) == 104U, "Cut sequence operation layout drift");
_Static_assert(sizeof(InkpodCutSequenceEditRequest) == 48U, "Cut sequence request layout drift");
_Static_assert(sizeof(InkpodCutSequenceEditResult) == 40U, "Cut sequence result layout drift");
_Static_assert(sizeof(InkpodDocumentThumbnailBuffer) == 56U, "document thumbnail layout drift");
_Static_assert(sizeof(InkpodResourceUsage) == 112U, "resource usage layout drift");
_Static_assert(sizeof(InkpodHistoryItem) == 24U, "history item layout drift");
_Static_assert(sizeof(InkpodStrokeSample) == 24U, "stroke sample layout drift");
_Static_assert(sizeof(InkpodStrokeInput) == 72U, "stroke input layout drift");
_Static_assert(sizeof(InkpodEditorBrushOptions) == 20U, "editor brush layout drift");
_Static_assert(sizeof(InkpodStrokeSampleSpan) == 40U, "stroke span layout drift");
_Static_assert(sizeof(InkpodViewInput) == 48U, "view input layout drift");
_Static_assert(sizeof(InkpodSnapshotTransform) == 48U, "snapshot transform layout drift");
_Static_assert(sizeof(InkpodSnapshotGuide) == 24U, "snapshot guide layout drift");
_Static_assert(sizeof(InkpodSnapshotOverlay) == 56U, "snapshot overlay layout drift");
_Static_assert(sizeof(InkpodShootingFrameInput) == 64U, "shooting frame input layout drift");
_Static_assert(sizeof(InkpodShootingFramePoint) == 16U, "shooting frame point layout drift");
_Static_assert(sizeof(InkpodShootingFrameInfo) == 136U, "shooting frame info layout drift");
_Static_assert(sizeof(InkpodSnapshotShootingFrameView) == 40U, "shooting frame view layout drift");
_Static_assert(sizeof(InkpodVanishingPointInput) == 72U, "vanishing point input layout drift");
_Static_assert(sizeof(InkpodVanishingPointInfo) == 80U, "vanishing point info layout drift");
_Static_assert(sizeof(InkpodSnapshotRadialGuide) == 80U, "radial guide layout drift");
_Static_assert(sizeof(InkpodSnapshotVanishingPointView) == 64U, "vanishing point view layout drift");
_Static_assert(sizeof(InkpodSnapshotVectorEndpoint) == 32U, "vector endpoint layout drift");
_Static_assert(sizeof(InkpodSnapshotVectorDiagnostics) == 40U, "vector diagnostics layout drift");
_Static_assert(sizeof(InkpodObjectId) == 32U, "object id layout drift");
_Static_assert(sizeof(InkpodPrimitiveRequestV3) == 120U, "primitive request layout drift");
_Static_assert(sizeof(InkpodPrimitiveResultV3) == 48U, "primitive result layout drift");
_Static_assert(sizeof(InkpodRasterAssetInputV3) == 56U, "raster asset layout drift");
_Static_assert(sizeof(InkpodObjectInfoV3) == 72U, "object info layout drift");
_Static_assert(sizeof(InkpodSnapshotInfoV3) == 104U, "snapshot info layout drift");
_Static_assert(sizeof(InkpodSnapshotTileInfoV3) == 56U, "snapshot tile info layout drift");
_Static_assert(sizeof(InkpodBufferCopyV3) == 56U, "buffer copy layout drift");
_Static_assert(sizeof(InkpodRasterSourceInput) == 96U, "raster source layout drift");
_Static_assert(sizeof(InkpodLightTableItemInput) == 168U, "light-table input layout drift");
_Static_assert(sizeof(InkpodSequenceCellInput) == 120U, "sequence cell layout drift");
_Static_assert(sizeof(InkpodSequenceInput) == 40U, "sequence input layout drift");
_Static_assert(sizeof(InkpodSequenceSwitchRequest) == 88U, "sequence switch request layout drift");
_Static_assert(sizeof(InkpodSequenceStepPlan) == 96U, "sequence step plan layout drift");
_Static_assert(sizeof(InkpodMotionCheckInput) == 16U, "motion input layout drift");
_Static_assert(sizeof(InkpodMotionFrame) == 40U, "motion frame layout drift");
_Static_assert(sizeof(InkpodLayerThumbnailBuffer) == 80U, "layer thumbnail layout drift");
_Static_assert(sizeof(InkpodScopedColorReplaceInput) == 120U, "scoped replace input layout drift");
_Static_assert(sizeof(InkpodScopedColorReplacePreview) == 48U, "scoped replace preview layout drift");
_Static_assert(sizeof(InkpodSequenceSourceIdentity) == 32U, "sequence identity layout drift");
_Static_assert(sizeof(InkpodBatchPairPreviewInfo) == 40U, "pair preview info layout drift");
_Static_assert(sizeof(InkpodBatchPairCandidate) == 64U, "pair candidate layout drift");
_Static_assert(sizeof(InkpodInkScriptSourceInput) == 56U, "InkScript source input layout drift");
_Static_assert(sizeof(InkpodInkScriptSourceSummary) == 72U, "InkScript source summary layout drift");
_Static_assert(sizeof(InkpodInkScriptUtf8Buffer) == 48U, "InkScript UTF-8 buffer layout drift");
_Static_assert(sizeof(InkpodInkScriptDiagnostic) == 128U, "InkScript diagnostic layout drift");
_Static_assert(sizeof(InkpodInkScriptDiagnosticBuffer) == 96U, "InkScript diagnostic buffer layout drift");
_Static_assert(sizeof(InkpodInkScriptParameterChoice) == 56U, "InkScript parameter choice layout drift");
_Static_assert(sizeof(InkpodInkScriptCompileRequest) == 80U, "InkScript compile request layout drift");
_Static_assert(sizeof(InkpodInkScriptProgramSummary) == 152U, "InkScript program summary layout drift");
_Static_assert(sizeof(InkpodInkScriptJournalEvent) == 24U, "InkScript event layout drift");
_Static_assert(sizeof(InkpodInkScriptExportRequest) == 96U, "InkScript export request layout drift");
_Static_assert(sizeof(InkpodInkScriptFragmentSummary) == 88U, "InkScript fragment summary layout drift");

int inkpod_header_c11_smoke(void) {
    InkpodSnapshotView view = {0};
    InkpodInkScriptSourceInput source = {0};
    view.struct_size = (uint32_t)sizeof(view);
    source.struct_size = (uint32_t)sizeof(source);
    source.version = INKPOD_INKSCRIPT_RECORD_VERSION;
    return view.struct_size == 0U || source.struct_size == 0U;
}
