[package]
name = "inkpod-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
inkpod-core = { path = "../inkpod-core" }
inkpod-format = { path = "../inkpod-format" }
inkpod-io = { path = "../inkpod-io" }

[lints]
workspace = true
