[package]
name = "inkpod-format-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
inkpod-format = { path = ".." }
inkpod-core = { path = "../../inkpod-core" }

[[bin]]
name = "native_v19"
path = "fuzz_targets/native_v9.rs"
test = false
doc = false
bench = false

[[bin]]
name = "native_core_v19"
path = "fuzz_targets/native_core_v9.rs"
test = false
doc = false
bench = false
