[package]
name = "inkpod-format-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
inkpod-format = { path = ".." }
inkpod-core = { path = "../../inkpod-core" }

[[bin]]
name = "native_v28"
path = "fuzz_targets/native_v28.rs"
test = false
doc = false
bench = false

[[bin]]
name = "native_core_v28"
path = "fuzz_targets/native_core_v28.rs"
test = false
doc = false
bench = false

[[bin]]
name = "cut_v28"
path = "fuzz_targets/cut_v28.rs"
test = false
doc = false
bench = false

[[bin]]
name = "tga_v2"
path = "fuzz_targets/tga_v2.rs"
test = false
doc = false
bench = false

[[bin]]
name = "inkscript_lexer_v2"
path = "fuzz_targets/inkscript_lexer_v2.rs"
test = false
doc = false
bench = false

[[bin]]
name = "inkscript_parser_v2"
path = "fuzz_targets/inkscript_parser_v2.rs"
test = false
doc = false
bench = false
