param(
    [Parameter(Mandatory = $false)]
    [string]$RepositoryRoot
)

$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrWhiteSpace($RepositoryRoot)) {
    $RepositoryRoot = Split-Path -Parent $PSScriptRoot
}
$utf8 = [System.Text.UTF8Encoding]::new($false)
$catalogPath = Join-Path $RepositoryRoot 'apps/windows/ui/localization_catalog.json'
$templatePath = Join-Path $RepositoryRoot 'apps/windows/app/app_ui.template.rc'
$idsPath = Join-Path $RepositoryRoot 'apps/windows/ui/localization_catalog_ids.generated.inc'
$tablePath = Join-Path $RepositoryRoot 'apps/windows/ui/localization_catalog.generated.inc'
$jaPath = Join-Path $RepositoryRoot 'apps/windows/app/app_ui_ja.generated.rc'
$enPath = Join-Path $RepositoryRoot 'apps/windows/app/app_ui_en.generated.rc'

function Normalize-Newlines([string]$Value) {
    return $Value.Replace("`r`n", "`n").Replace("`r", "`n")
}

function Cpp-Quote([string]$Value) {
    $builder = [System.Text.StringBuilder]::new('L"')
    foreach ($character in $Value.ToCharArray()) {
        $code = [int]$character
        if ($code -eq 0) {
            [void]$builder.Append('\0')
        } elseif ($code -eq 9) {
            [void]$builder.Append('\t')
        } elseif ($code -eq 10) {
            [void]$builder.Append('\n')
        } elseif ($code -eq 13) {
            [void]$builder.Append('\r')
        } elseif ($code -eq 34) {
            [void]$builder.Append('\"')
        } elseif ($code -eq 92) {
            [void]$builder.Append('\\')
        } elseif ($code -lt 32) {
            [void]$builder.AppendFormat('\u{0:x4}', $code)
        } else {
            [void]$builder.Append($character)
        }
    }
    [void]$builder.Append('"')
    return $builder.ToString()
}

function Rc-Quote([string]$Value) {
    # rc.exe does not decode JSON Unicode escapes such as \u0026. Reuse the
    # C-style escaping above and remove only the wide-string prefix.
    return (Cpp-Quote $Value).Substring(1)
}

function Menu-Label([string]$Value, [string]$Key, [string]$Language) {
    if ($Key.Length -ne 1 -or $Key -cnotmatch '^[A-Z0-9]$') {
        throw "Invalid menu mnemonic key: $Key"
    }
    if ($Value.Contains('&')) {
        throw "Menu source text must not contain an ampersand: $Value"
    }
    $parts = $Value.Split([char]9, 2)
    $label = $parts[0]
    if ($Language -eq 'en') {
        $position = $label.IndexOf($Key, [StringComparison]::OrdinalIgnoreCase)
        if ($position -lt 0) {
            throw "English menu label '$label' does not contain mnemonic '$Key'"
        }
        $label = $label.Insert($position, '&')
    } else {
        $ellipsis = ''
        if ($label.EndsWith('...')) {
            $label = $label.Substring(0, $label.Length - 3)
            $ellipsis = '...'
        } elseif ($label.EndsWith('…')) {
            $label = $label.Substring(0, $label.Length - 1)
            $ellipsis = '…'
        }
        $label += "(&$Key)$ellipsis"
    }
    if ($parts.Count -eq 2) {
        $label += "`t$($parts[1])"
    }
    return $label
}

$catalogText = Normalize-Newlines ([IO.File]::ReadAllText($catalogPath, $utf8))
$catalog = $catalogText | ConvertFrom-Json
$sha = [Security.Cryptography.SHA256]::Create()
try {
    $hashBytes = $sha.ComputeHash($utf8.GetBytes($catalogText))
} finally {
    $sha.Dispose()
}
$hash = -join ($hashBytes | ForEach-Object { $_.ToString('x2') })
$banner = "// Generated from apps/windows/ui/localization_catalog.json.`n" +
    "// Catalog SHA-256: $hash`n" +
    "// Do not edit this file directly.`n"

$ids = [Text.StringBuilder]::new($banner)
$table = [Text.StringBuilder]::new($banner)
$byId = @{}
foreach ($entry in $catalog.entries) {
    $byId[$entry.id] = $entry
    [void]$ids.Append("INKPOD_UI_STRING_ID($($entry.id))`n")
    [void]$table.Append('{')
    [void]$table.Append((Cpp-Quote $entry.ja))
    [void]$table.Append(", $($entry.ja.Length)U, ")
    [void]$table.Append((Cpp-Quote $entry.en))
    [void]$table.Append(", $($entry.en.Length)U},`n")
}

function Generate-Resource([string]$Language, [string]$LanguageId) {
    $template = Normalize-Newlines ([IO.File]::ReadAllText($templatePath, $utf8))
    $body = [regex]::Replace(
        $template,
        '@INKPOD_UI_MENU_([A-Za-z][A-Za-z0-9_]*)_([A-Z0-9])@',
        {
            param($match)
            $entry = $byId[$match.Groups[1].Value]
            if ($null -eq $entry) {
                throw "Unknown menu localization marker: $($match.Groups[1].Value)"
            }
            $value = if ($Language -eq 'ja') { $entry.ja } else { $entry.en }
            return Rc-Quote (Menu-Label ([string]$value) $match.Groups[2].Value $Language)
        })
    $body = [regex]::Replace(
        $body,
        '@INKPOD_UI_TEXT_([A-Za-z][A-Za-z0-9_]*)@',
        {
            param($match)
            $entry = $byId[$match.Groups[1].Value]
            if ($null -eq $entry) {
                throw "Unknown localization marker: $($match.Groups[1].Value)"
            }
            $value = if ($Language -eq 'ja') { $entry.ja } else { $entry.en }
            return Rc-Quote ([string]$value)
        })
    return $banner + "#include <windows.h>`n#include <commctrl.h>`n#include `"resource.h`"`n`n" +
        "#pragma code_page(65001)`nLANGUAGE $LanguageId`n`n" + $body
}

[IO.File]::WriteAllText($idsPath, $ids.ToString(), $utf8)
[IO.File]::WriteAllText($tablePath, $table.ToString(), $utf8)
[IO.File]::WriteAllText(
    $jaPath,
    (Generate-Resource 'ja' 'LANG_JAPANESE, SUBLANG_JAPANESE_JAPAN'),
    $utf8)
[IO.File]::WriteAllText(
    $enPath,
    (Generate-Resource 'en' 'LANG_ENGLISH, SUBLANG_ENGLISH_US'),
    $utf8)
