#!/usr/bin/env python3
"""Generate the exact-current InkScript command reference.

The checked-in Markdown is derived only from the frozen language and production
catalog registries. Normal builds do not require Python; ``--check`` is the
authoritative drift check and ``--write`` refreshes the generated artifact.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from typing import Any


ROOT = pathlib.Path(__file__).resolve().parents[1]
LANGUAGE_PATH = ROOT / "schemas" / "inkscript" / "language-v2.json"
CATALOG_PATH = ROOT / "schemas" / "inkscript" / "catalog-v4.json"
REFERENCE_PATH = ROOT / "docs" / "inkscript-command-reference.md"


def compact(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def inline(value: str) -> str:
    return f"`{value.replace('`', '&#96;')}`"


def fnv1a64_normalized(data: bytes) -> int:
    value = 0xCBF29CE484222325
    for byte in data.replace(b"\r\n", b"\n").replace(b"\r", b""):
        value = ((value ^ byte) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return value


def field_signature(field: dict[str, Any]) -> str:
    suffix = "" if field["required"] else "?"
    details: list[str] = []
    if not field["required"]:
        details.append("default=" + compact(field.get("default")))
    if field.get("nullable") is True:
        details.append("nullable")
    bounds = field.get("bound", field.get("constraints", []))
    if bounds:
        details.append("bound=" + ",".join(bounds))
    role = field.get("stable_id_role")
    if role is not None:
        details.append(
            "id=" + role["name"] + ":" + role["namespace"] + ":" + role["cardinality"]
        )
    asset = field.get("asset_role")
    if asset is not None:
        details.append(
            "asset="
            + asset["name"]
            + ":"
            + asset["kind"]
            + f":inline={str(asset['inline']).lower()}:external={str(asset['external']).lower()}"
        )
    detail = " [" + "; ".join(details) + "]" if details else ""
    return f"{field['name']}{suffix}: {field['type']}{detail}"


def result_signature(result: dict[str, Any]) -> str:
    details = [result["availability"], result["cardinality"]]
    if result["namespace"] is not None:
        details.append("namespace=" + result["namespace"])
    if result["owner_role"] is not None:
        details.append("role=" + result["owner_role"])
    if result["output_id_ordinal"] is not None:
        details.append("output=" + str(result["output_id_ordinal"]))
    return f"{result['name']}: {result['type']} [{'; '.join(details)}]"


def render() -> str:
    language = json.loads(LANGUAGE_PATH.read_text(encoding="utf-8"))
    catalog_bytes = CATALOG_PATH.read_bytes()
    catalog = json.loads(catalog_bytes.decode("utf-8"))
    if language.get("kind") != "inkpod.inkscript.language":
        raise RuntimeError("invalid language registry identity")
    if catalog.get("kind") != "inkpod.inkscript.catalog" or catalog.get("production") is not True:
        raise RuntimeError("catalog is not the frozen production registry")
    if (
        language["file_version"] != catalog["file_version"]
        or language["procedure_catalog_version"] != catalog["catalog_version"]
        or language["required_replay_epoch"] != catalog["required_replay_epoch"]
        or len(catalog["entries"]) != 75
    ):
        raise RuntimeError("language/catalog exact-current versions disagree")

    lines = [
        "<!-- @generated by scripts/generate_inkscript_reference.py; do not edit. -->",
        "",
        "# InkScript command reference",
        "",
        "This reference is generated from the exact-current language and production catalog registries.",
        "The JSON registries remain normative when this presentation differs.",
        "",
        "## Contract",
        "",
        "| Contract | Exact-current value |",
        "| --- | ---: |",
        f"| Registry schema | {language['registry_schema_version']} |",
        f"| InkScript file | {language['file_version']} |",
        f"| Procedure catalog | {catalog['catalog_version']} |",
        f"| Required replay epoch | {language['required_replay_epoch']} |",
        f"| Commands | {len(catalog['entries'])} |",
        f"| Catalog FNV-1a drift fingerprint | `{fnv1a64_normalized(catalog_bytes):016x}` |",
        "",
        "## Language selectors",
        "",
        "| Name | Reference type | Owner | Initial order |",
        "| --- | --- | --- | --- |",
    ]
    for selector in language["selector_entities"]:
        lines.append(
            f"| {inline(selector['name'])} | {inline(selector['reference_type'])} | "
            f"{inline(selector['owner'])} | {inline(selector['initial_order'])} |"
        )

    lines.extend(
        [
            "",
            "## Language assertions",
            "",
            "| Name | Comparison | Failure |",
            "| --- | --- | --- |",
        ]
    )
    for assertion in language["assert_kinds"]:
        lines.append(
            f"| {inline(assertion['name'])} | {inline(assertion['comparison'])} | "
            f"{inline(assertion['failure'])} |"
        )

    lines.extend(
        [
            "",
            "## Language assets",
            "",
            "| Name | Descriptor | Inline | External |",
            "| --- | --- | ---: | ---: |",
        ]
    )
    for asset in language["asset_kinds"]:
        lines.append(
            f"| {inline(asset['name'])} | {inline(asset['descriptor_type'])} | "
            f"{str(asset['inline']).lower()} | {str(asset['external']).lower()} |"
        )

    lines.extend(["", "## Catalog enums", ""])
    for enum in catalog["enums"]:
        lines.append(f"- {inline(enum['name'])}: " + ", ".join(inline(value) for value in enum["members"]))

    lines.extend(["", "## Catalog constructors", ""])
    for constructor in catalog["constructors"]:
        arguments = ", ".join(
            f"{value['name']}: {value['type']}" for value in constructor["arguments"]
        )
        lines.append(
            f"- {inline(constructor['name'] + '(' + arguments + ') -> ' + constructor['result'])}"
        )

    lines.extend(["", "## Catalog records", ""])
    for record in catalog["records"]:
        fields = "; ".join(field_signature(field) for field in record["fields"])
        lines.append(f"- {inline(record['name'])}: {fields or 'none'}")

    lines.extend(["", "## Commands", ""])
    for entry in catalog["entries"]:
        arguments = "; ".join(field_signature(value) for value in entry["arguments"]) or "none"
        results = "; ".join(result_signature(value) for value in entry["results"]) or "none"
        portability = entry["portability"]
        default = portability["default"]
        default_text = default["class"]
        if default["required_preconditions"]:
            default_text += " (" + ", ".join(default["required_preconditions"]) + ")"
        work = "; ".join(
            f"{name}={compact(value)}" for name, value in entry["work"].items()
        )
        editor = entry["editor"]
        lines.extend(
            [
                f"### {inline(entry['name'])}",
                "",
                f"- Primitive: {inline(entry['primitive_id'])}; schema {entry['primitive_schema_version']}; "
                f"semantics {entry['semantics_revision']}; replay epoch {entry['replay_epoch']}.",
                f"- Arguments: {arguments}.",
                f"- Results: {results}.",
                f"- Portability: {default_text}; ordered rules: {len(portability['rules'])} "
                f"({compact(portability['rules'])}).",
                f"- Work: {work}; cancellation: {inline(entry['cancellation_boundary'])}.",
                f"- Editor: family {inline(editor['family'])}; legacy projection "
                f"{inline(editor['legacy_projection']) if editor['legacy_projection'] is not None else 'none'}; "
                f"skip dependents {str(editor['allow_skip_dependents']).lower()}.",
                f"- Ownership: {inline(entry['owner_milestone'])}; equivalence {inline(entry['equivalence_test'])}.",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true")
    group.add_argument("--write", action="store_true")
    args = parser.parse_args()
    generated = render()
    if args.write:
        REFERENCE_PATH.write_text(generated, encoding="utf-8", newline="\n")
        return 0
    actual = REFERENCE_PATH.read_text(encoding="utf-8") if REFERENCE_PATH.exists() else ""
    if actual != generated:
        print(
            "generated InkScript command reference is stale; run "
            "scripts/generate_inkscript_reference.py --write",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
